### ISSUE TITLE
Remove type piracy for Base.show

### ISSUE THREAD

**Issue by davidanthoff** [jw3126/Setfield.jl#113]
[This](https://github.com/jw3126/Setfield.jl/blob/v0.5.3/src/sugar.jl#L311) method for `Base.show` causes all sorts of trouble. For example, it breaks `methods(Base.show)`. It also takes down the symbol server julia process for the VS Code extension with a segfault...

I think at the end of the day this is a particularly bad case of type piracy because it really breaks julia base. Could you remove it sooner rather than later and tag a new release?

**Comment by tkf** [comment]
We discussed this and initially rejected the idea as we were aware of the danger https://github.com/jw3126/Setfield.jl/pull/77#issuecomment-530664735 but then I _thought_ the bug that caused trouble due to a missimplementation of `Type{<:MyType}` was fixed https://github.com/jw3126/Setfield.jl/issues/85.  But I think we should remove this if it is causing troubles.

Out of curiosity, do you have a MWE for the segfault?

**Comment by davidanthoff** [comment]
Reading through these threads, its pretty clear that Jeff strongly discourages adding such a `show` method in the first place (irrespective of whether it crashes or not), so I think it should just be removed, crash or not.

I can reproduce the error, but only in a super complicated setup within the VS Code extension story, so nothing like a MWE. At some point it shows an undef var `f` error, and then everything crashes. That seems the same error that I mentioned above, just with more dire consequences when it happens in the VS Code context.
