### ISSUE TITLE
 constructor_of(T::UnionAll)

### ISSUE THREAD

**Issue by jw3126** [jw3126/Setfield.jl#26]
https://github.com/jw3126/Setfield.jl/blob/940d72bccef97a47128a9ced3335b0c83d3a089e/src/lens.jl#L112
@tkf I would like to add a testcase for this, can you give an example, where this is needed?

**Comment by tkf** [comment]
It was required for something like `constructor_of(Vector) == Array`. I copied that from my other code. But in our usage, there is no chance that a type with unbound type parameters (i.e., `UnionAll`) is passed to `constructor_of` since it is `typeof` an instance (No object can do `typeof(...) == UnionAll`, right?). I think we can remove it.

**Comment by jw3126** [comment]
Okay thanks for explaining and solving this!
